#!/bin/bash

set -e

ZWACONF=./.zwaconf

TARGET=
CONFIGURE_SHELL=

get_version(){
      head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
}

sed_file() {

    while [ -n "$1" ]; do
        in=$1.in
        out=$1

        sed \
            -e "s/@VERSION@/${VERSION}/g" \
            $in > $out
        shift
    done
}

if [ -f $ZWACONF ]; then
  . $ZWACONF
fi

if [ -z "$TARGET" ]; then
  TARGET=$PWD/out
fi

if [ -z "$MAKE" ];then
  MAKE=make
fi

cmd=$1
shift
case "$cmd" in
  get-version)
    get_version
    ;;
  prepare-dist)
    VERSION=`get_version`
    ;;
  dist-exclude-list|build-exclude-list)
    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ;;
  bootstrap)
      mkdir -p m4
      libtoolize -i -c -f
      aclocal -I m4
      autoconf
      ./configure --disable-amalgamation
      $MAKE sqlite3.h
      mv sqlite3.h sqlite3.h-bb
      $MAKE distclean
    ;;
  configure)
    OPTIONS=`getopt -l "help,shell:,prefix:" 'p:s:' $*`
    if [ $? -ne 0 ]; then
      echo "$0: unknown flags..."
      exit 1
    fi

    eval set -- "$OPTIONS"
    while true ; do
      _arg=$1

      if [ -z "$_arg" ]; then
        break
      fi
      case $1 in
        -p|--prefix)
          shift
          TARGET="$1"
          ;;
        --prefix=*)
          TARGET=${1##*=}
          ;;
        -s|--shell)
          shift
          CONFIGURE_SHELL="$1"
          ;;
        --shell=*)
          CONFIGURE_SHELL=${1##*=}
          ;;
      esac
      shift
    done
    echo "TARGET=$TARGET" > $ZWACONF
    CONFOPTS=
    if echo "$ZBS_DIST" | grep '^linux' >/dev/null 2>&1 && [ -n "$ZBS_ARCH" ] && [ "$ZBS_ARCH" = "i386" ];then
      CONFOPTS=--build=$ZBS_ARCH-unknown-`uname | tr '[A-Z]' '[a-z]'`-gnu
    fi
    if echo "$ZBS_DIST" | grep '^aix' >/dev/null 2>&1;then
      CFLAGS="$CFLAGS -DSQLITE_DISABLE_DIRSYNC -DSQLITE_DEBUG=1"
    fi
    #LDFLAGS="$LDFLAGS -Wl,-O1" \
    # variables ripped from Ubuntu zlib packaging
    #unset CFLAGS LDFLAGS CC
    CFLAGS=`echo $CFLAGS | sed -e 's/-I[^ ]*//g'`

    # force using -pthread for gcc. Otherwise configure "forgets" to set the
    # thread related compiler options...
    CFLAGS="$CFLAGS -pthread"
    LDFLAGS="$LDFLAGS -pthread"
    export CFLAGS LDFLAGS
    $CONFIGURE_SHELL ./configure --prefix $TARGET --disable-tcl --disable-readline --disable-amalgamation \
                 --enable-shared --enable-static --disable-tcl --enable-threadsafe \
                 --enable-cross-thread-connections $CONFOPTS

    cp sqlite3.h-bb sqlite3.h
    touch sqlite3.h
    ;;
  make)
    case $1 in
      distclean)
        $MAKE distclean || true
        for p in debian/patches/*; do
          patch -R -N -p1< $p
        done
        autoconf
        ;;
      *) # unset CFLAGS LDFLAGS CC
        $MAKE $@
        ;;
    esac
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
