name: sqlite3
builder:
  name: BalabitBuilder
  configure_options: "--disable-tcl --disable-readline --disable-amalgamation --enable-shared --disable-static  --disable-tcl --enable-threadsafe  --enable-cross-thread-connections --enable-debug"
  flags: "no-make-dist"
  # dist_hook needs because builder machines usually
  # have not tclsh binary, but normally tclsh is required by creating sqlite3.h
  prepare_dist_hook: "/bin/sh -c 'make sqlite3.h && mv sqlite3.h sqlite3.h-bb'"
platforms:
  - aix-6.1/powerpc
  - linux-glibc2.11/amd64
